apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}-secret
  labels:
  {{- include "redis.labels" . | nindent 4 }}
  annotations:
    avp.kubernetes.io/path: avp/data/result
stringData:
  success: {{ required "secret.success is required" .Values.secret.success | quote
    }}
type: Opaque
