apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: color-applicationset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - namespace: dev
      - namespace: uat
      - namespace: prod
  template:
    metadata:
      # will generate applications with different names for example (dev-color-app, uat-color-app, etc..)
      name: '{{namespace}}-color-app'
    spec:
      # applications will be in default project for argocd
      project: default
      source:
        repoURL: https://github.com/rutwickjain87/argocd-sample-apps.git
        targetRevision: HEAD
        path: demo/list-generator-example/deployment
      destination:
        # default cluster as destination, you can define multiple clusters in ArgoCD UI
        server: https://kubernetes.default.svc
        # will deploy to different namespaces as different destinations 
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true

