apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "balance-cache.fullname" . }}-balance-cache-config
  labels:
  {{- include "balance-cache.labels" . | nindent 4 }}
data:
  balance-cache-config: {{ .Values.balanceCacheConfig.balanceCacheConfig | toYaml
    | indent 1 }}