apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix:  dev-

helmGlobals:
  chartHome: charts

helmCharts:
- name: balance-cache
  releaseName: balance-cache
  namespace: default
